version: "3.7"
services:
  # postgres + pgadmin4 web UI
  postgres:
    container_name: postgres
    # 16.1
    image: docker.io/postgres:16.1-alpine3.19
    volumes:
      - ${REMOTE_PROJECT_PATH:-.}/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_MULTIPLE_DATABASES: spring_join
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "$${POSTGRES_USER}"]
      timeout: 1s
      interval: 10s
      start_period: 10s
  pgadmin4:
    container_name: pgadmin4
    # 6.9
    image: docker.io/dpage/pgadmin4:8.1
    volumes:
      - ${REMOTE_PROJECT_PATH:-.}/pgadmin4/pgadmin4/servers.json:/pgadmin4/servers.json:ro
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    depends_on:
      postgres:
        condition: "service_healthy"
    ports:
      - "8091:80"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:80/misc/ping"]
      timeout: 1s
      interval: 10s
      start_period: 2m
